Use larger keys for nsd-control in tdir tests
Because newer OpenSSL fails on the small keys:
error: error in SSL_CTX use_certificate_chain_file crypto error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small