Fix Hurd build error due to log_err.
Build log at https://buildd.debian.org/status/fetch.php?pkg=nsd&arch=hurd-i386&ver=4.9.1-1&stamp=1712912870&raw=0
failing like this:

util.c: In function ‘set_cpu_affinity’:
util.c:1226:9: error: implicit declaration of function ‘log_err’ [-Werror=implicit-function-declaration]
 1226 |         log_err("sched_setaffinity: not available on this system");
      |         ^~~~~~~
cc1: some warnings being treated as errors

Signed-off-by: Simon Josefsson <simon@josefsson.org>